### ISSUE TITLE
Feature request: Deploying VM's in scalesets

### ISSUE THREAD

**Issue by sanderkooger** [microsoft/openshift-origin#37]
At the moment the VM's are deployed into an Availability set. making it hard to add node infra servers and masters to a cluster. 

Would it be possible to deploy the machines into a scale set so we can introduce autoscale? Openshift best practice says that horizontal scaling is one of the most important features but this is currently not possible in Azure using this template. 

I would be even better if we could deploy the same template for both a DEV environment and a Live environment where dev only needs one master and one infra VM to save costs. 

Edit: Typos

**Comment by haroldwongms** [comment]
In order to use VMSS, we need to use Managed Disks.  In the current release of OpenShift, support for Managed Disks is not at it's best so we were waiting for 3.7.  Also, moving forward, OpenShift will no longer be supporting single master configurations so Boris and I made the decision to move to a minimum of 3 masters now versus waiting.
